### ISSUE TITLE
Too many translation files in index

### ISSUE THREAD

**Issue by piotrooo** [letsdrink/ouzo-phpstorm-plugin#55]
```
Too many translation files in index: file:///home/piotr/thulium/vagrant/hg/system/panel/panel2.0/locales/pl.php, file:///home/piotr/thulium/vagrant/hg/system/panel/panel2.0/locales/en.php
java.lang.IllegalStateException: Too many translation files in index: file:///home/piotr/thulium/vagrant/hg/system/panel/panel2.0/locales/pl.php, file:///home/piotr/thulium/vagrant/hg/system/panel/panel2.0/locales/en.php
	at com.github.letsdrink.intellijplugin.translation.MissingTranslationAnnotator$1.handleKey(MissingTranslationAnnotator.java:52)
	at com.github.letsdrink.intellijplugin.translation.TranslationCallParser.parse(TranslationCallParser.java:25)
	at com.github.letsdrink.intellijplugin.translation.MissingTranslationAnnotator.collectInformation(MissingTranslationAnnotator.java:41)
	at com.github.letsdrink.intellijplugin.translation.MissingTranslationAnnotator.collectInformation(MissingTranslationAnnotator.java:25)
	at com.intellij.lang.annotation.ExternalAnnotator.collectInformation(ExternalAnnotator.java:57)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:100)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

PhpStorm 10.0.2
Build 143.790

**Comment by woru** [comment]
ouzo project path was not configured
